# 1. Testing Dataset object

In [64]:
from si.data.dataset_module import Dataset
import numpy as np

In [65]:
# create a dataset
X = np.random.rand(50, 3)
y = np.random.randint(0, 2, 50)
features = ['1', '2', '3']
label = 'y'
dataset = Dataset(X, y, features, label)

In [66]:
dataset.shape()

(50, 3)

In [67]:
dataset.X

array([[0.21297314, 0.11603796, 0.59794077],
       [0.16594932, 0.28654393, 0.07031028],
       [0.33733168, 0.72249666, 0.72588555],
       [0.33940697, 0.59058792, 0.08415238],
       [0.25168877, 0.41079277, 0.51342521],
       [0.65308556, 0.0077654 , 0.23498334],
       [0.64766444, 0.93568986, 0.22880375],
       [0.68219148, 0.35660682, 0.17762595],
       [0.03145186, 0.96586586, 0.32398335],
       [0.28465905, 0.10191172, 0.96095604],
       [0.53408834, 0.71832925, 0.03054765],
       [0.07160023, 0.67695408, 0.75831185],
       [0.71176014, 0.81282196, 0.88105899],
       [0.47262807, 0.76301546, 0.680144  ],
       [0.86536999, 0.16054223, 0.1889809 ],
       [0.68640567, 0.84592669, 0.13645401],
       [0.4699762 , 0.18233375, 0.28394094],
       [0.46864681, 0.29404307, 0.17095275],
       [0.43279107, 0.13618103, 0.1329044 ],
       [0.68648641, 0.42187329, 0.69150391],
       [0.17054451, 0.09615277, 0.07207546],
       [0.25208704, 0.51429987, 0.34112289],
       [0.

In [69]:
dataset.features_names

['1', '2', '3']

In [70]:
# Supervised or unsupervised
dataset.has_label()

True

In [71]:
# Print the label
dataset.y

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0])

In [72]:
dataset.get_classes()

array([0, 1])

In [73]:
dataset.summary()

mean    median  variance       min       max
0  0.461746  0.458137  0.070446  0.016386  0.960505
1  0.474581  0.436894  0.092496  0.001155  0.984303
2  0.423950  0.358085  0.093915  0.026038  0.988758

In [80]:
from si.io_package.data_file import read_data_file

# read breast dataset from data file
filename = r'C:\Users\Ana\Documents\GitHub\mbioinf-sib\datasets\breast-bin.data'
breast_dataset = read_data_file(filename, sep=',', label=True)

TypeError: __init__() missing 2 required positional arguments: 'features_names' and 'label_names'

In [57]:
breast_dataset.summary()

NameError: name 'breast_dataset' is not defined

In [ ]:
breast_dataset.y

In [ ]:
print('Features', breast_dataset.features)
print('Label', breast_dataset.label)

In [58]:
# write the same fila with a different name
from si.io_package.data_file import write_data_file
write_data_file('../datasets/breast-bin_tabular.tsv', breast_dataset, sep='\t', label=True)

NameError: name 'breast_dataset' is not defined

In [ ]:
from si.io_package.csv import read_csv

# read iris dataset from data file
iris_dataset = read_csv('../datasets/iris.csv', sep=',', features=True, label=True)
iris_dataset.summary()

In [ ]:
iris_dataset.get_classes()

In [ ]:
# write the same file with a different name
from si.io_package.csv import write_csv
write_csv('../datasets/iris_tabular.tsv', iris_dataset, sep='\t', features=True, label=True)