# 1. Testing Dataset object

In [1]:
from si.data.dataset_module import Dataset
import numpy as np

In [2]:
# create a dataset
X = np.random.rand(50, 3)
y = np.random.randint(0, 2, 50)
features = ['1', '2', '3']
label = 'y'
dataset = Dataset(X, y, features, label)

In [3]:
dataset.shape()

(50, 3)

In [4]:
dataset.X

array([[0.08267321, 0.31799891, 0.6678633 ],
       [0.4630569 , 0.77530919, 0.10238716],
       [0.02063998, 0.77024575, 0.31014046],
       [0.93082336, 0.81028871, 0.58111003],
       [0.49175199, 0.47446634, 0.52151527],
       [0.53899442, 0.10432191, 0.20988616],
       [0.04256587, 0.42443615, 0.60340006],
       [0.82899144, 0.69703083, 0.8785475 ],
       [0.17618625, 0.61055537, 0.1631975 ],
       [0.54552218, 0.65879149, 0.74118017],
       [0.29806305, 0.56406446, 0.57486697],
       [0.79821928, 0.94612863, 0.50277181],
       [0.05474293, 0.85525787, 0.54033265],
       [0.27363911, 0.26369912, 0.89472469],
       [0.4779716 , 0.46082809, 0.08478402],
       [0.83760228, 0.2157024 , 0.2514338 ],
       [0.41794557, 0.54890129, 0.94497719],
       [0.16256941, 0.6059596 , 0.87810856],
       [0.3057696 , 0.83577196, 0.2345844 ],
       [0.82405685, 0.52402511, 0.41018496],
       [0.70266517, 0.58454929, 0.96596482],
       [0.97261728, 0.14369607, 0.06151624],
       [0.

In [5]:
dataset.features_names

['1', '2', '3']

In [6]:
# Supervised or unsupervised
dataset.has_label()

True

In [7]:
# Print the label
dataset.y

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1])

In [8]:
dataset.get_classes()

array([0, 1])

In [9]:
dataset.summary()

mean    median  variance       min       max
0  0.523903  0.507896  0.087992  0.020640  0.972617
1  0.556587  0.570181  0.055185  0.087503  0.991098
2  0.548238  0.557978  0.087866  0.017541  0.980539

In [10]:
from si.io_package.data_file import read_data_file

# read breast dataset from data file
filename = r'C:\Users\Ana\Documents\GitHub\mbioinf-sib\datasets\breast-bin.data'
breast_dataset = read_data_file(filename, sep=',', label=True)

In [11]:
breast_dataset.summary()

mean  median   variance  min   max
0  4.417740     4.0   7.917053  1.0  10.0
1  3.134478     1.0   9.298082  1.0  10.0
2  3.207439     1.0   8.819630  1.0  10.0
3  2.806867     1.0   8.141527  1.0  10.0
4  3.216023     2.0   4.896110  1.0  10.0
5  3.486409     1.0  13.099601  1.0  10.0
6  3.437768     3.0   5.937114  1.0  10.0
7  2.866953     1.0   9.311340  1.0  10.0
8  1.589413     1.0   2.937284  1.0  10.0

In [12]:
breast_dataset.y

array([1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 0.

In [17]:
print('Features: ', breast_dataset.features_names)
print('Label:', breast_dataset.label_names)

Features:  None
Label: y


In [19]:
# write the same fila with a different name
from si.io_package.data_file import write_data_file
write_data_file(r'C:/Users/Ana/Documents/GitHub/mbioinf-sib/datasets/breast-bin_tabular.tsv', breast_dataset, sep='\t', label=True)

In [20]:
from si.io_package.csv_file import read_csv

# read iris dataset from data file
filename = r'C:\Users\Ana\Documents\GitHub\mbioinf-sib\datasets\iris.csv'
iris_dataset = read_csv(filename, sep=',', features=True, label=True)

In [21]:
iris_dataset.summary()

mean  median  variance  min  max
0  5.843333    5.80  0.681122  4.3  7.9
1  3.054000    3.00  0.186751  2.0  4.4
2  3.758667    4.35  3.092425  1.0  6.9
3  1.198667    1.30  0.578532  0.1  2.5

In [22]:
iris_dataset.get_classes()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [23]:
# write the same file with a different name
from si.io_package.csv_file import write_csv
write_csv(r'C:/Users/Ana/Documents/GitHub/mbioinf-sib/datasets/iris_tabular.tsv', iris_dataset, sep='\t', features=True, label=True)